## Vectors
#### A vector is a one-dimensional array of numbers. We can perform a variety of operations on vectors, such as addition, subtraction, scalar multiplication, and dot product.

### Creating a Vector

In [1]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

print("Vector 1: ", vector1)
print("Vector 2: ", vector2)

Vector 1:  [1 2 3]
Vector 2:  [4 5 6]


### Vector Operations

#### Vector Addition
Vector addition is performed by adding corresponding elements of each vector. This requires both vectors to be the same length.

In [2]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

addition = vector1 + vector2

print("Vector 1: ", vector1)
print("Vector 2: ", vector2)
print("Addition: ", addition)

Vector 1:  [1 2 3]
Vector 2:  [4 5 6]
Addition:  [5 7 9]


 Explanation: 
     For vectors [1, 2, 3] and [4, 5, 6], 
     the addition is:
        [1+4, 2+5, 3+6] -> [5, 7, 9]

#### Vector Subtraction
Similar to addition, vector subtraction is element-wise.

In [3]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

subtraction = vector1 - vector2

print("Vector 1: ", vector1)
print("Vector 2: ", vector2)
print("Subtraction:", subtraction)

Vector 1:  [1 2 3]
Vector 2:  [4 5 6]
Subtraction: [-3 -3 -3]


 Explanation: For vectors [1, 2, 3] and [4, 5, 6], the subtraction is:[1-4, 2-5, 3-6] -> [-3, -3, -3]

#### Scalar Multiplication

In scalar multiplication, each element of the vector is multiplied by a constant (scalar).

In [5]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

scalar_multiplication = 3 * vector1

print("Vector 1: ", vector1)
print("Vector 2: ", vector2)
print("Scalar Multiplication:", scalar_multiplication)

Vector 1:  [1 2 3]
Vector 2:  [4 5 6]
Scalar Multiplication: [3 6 9]


 Explanation: If we multiply [1, 2, 3] by 3, the result is:[3 * 1, 3 * 2, 3 * 3] -> [3, 6, 9]

#### Dot Product
The dot product is the sum of the products of corresponding elements of two vectors. It’s only possible when both vectors are of the same length.

In [6]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

dot_product = np.dot(vector1, vector2)

print("Vector 1: ", vector1)
print("Vector 2: ", vector2)
print("Dot Product:", dot_product)

Vector 1:  [1 2 3]
Vector 2:  [4 5 6]
Dot Product: 32


 Explanation: For vectors [1, 2, 3] and [4, 5, 6], the dot product is:(1 * 4) + (2 * 5) + (3 * 6) -> 4 + 10 + 18 = 32

## Matrices
#### A matrix is a two-dimensional array with rows and columns. Matrix operations include addition, subtraction, scalar multiplication, matrix multiplication, and transpose.

In [10]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

print("Matrix 1:\n", matrix1)
print("\n")
print("Matrix 2: \n", matrix2)

Matrix 1:
 [[1 2]
 [3 4]]


Matrix 2: 
 [[5 6]
 [7 8]]


### Matrix Operations

#### Matrix Addition
To add matrices, they must be of the same dimensions, and we add corresponding elements.

In [11]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_addition = matrix1 + matrix2

print("Matrix 1:\n", matrix1)
print("\n")
print("Matrix 2: \n", matrix2)
print("\n")
print("Matrix Addition:\n", matrix_addition)

Matrix 1:
 [[1 2]
 [3 4]]


Matrix 2: 
 [[5 6]
 [7 8]]


Matrix Addition:
 [[ 6  8]
 [10 12]]


 Explanation: For matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]], the addition is:[1+5    2+6]
[3+7    4+8] -> [[6, 8],   [10, 12]]

#### Matrix Subtraction
Similar to addition, matrix subtraction is element-wise.

In [12]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_subtraction = matrix1 - matrix2

print("Matrix 1:\n", matrix1)
print("\n")
print("Matrix 2: \n", matrix2)
print("\n")
print("Matrix Subtraction:\n", matrix_subtraction)

Matrix 1:
 [[1 2]
 [3 4]]


Matrix 2: 
 [[5 6]
 [7 8]]


Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]


 Explanation: For matrices [[1, 2], [3, 4]] and [[5, 6], [7, 8]], the subtraction is:[1-5  2-6]
[3-7  4-8] -> [[-4, -4], [-4, -4]]

#### Scalar Multiplication
Each element in the matrix is multiplied by the scalar.

In [14]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

scalar_multiplication = 2 * matrix1

print("Matrix 1:\n", matrix1)
print("\n")
print("Matrix 2: \n", matrix2)
print("\n")
print("Scalar Multiplication:\n", scalar_multiplication)

Matrix 1:
 [[1 2]
 [3 4]]


Matrix 2: 
 [[5 6]
 [7 8]]


Scalar Multiplication:
 [[2 4]
 [6 8]]


Explanation: If we multiply [[1, 2], [3, 4]] by 2, the result is:[2 * 1    2 * 2]
[2 * 3    2 * 4] -> [[2, 4], [6, 8]]

#### Matrix Multiplication (Dot Product)

Matrix multiplication is different from element-wise multiplication. For two matrices A (of dimensions m x n) and B (of dimensions n x p), the resulting matrix will have dimensions m x p.

In [15]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

matrix_multiplication = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("\n")
print("Matrix 2: \n", matrix2)
print("\n")
print("Matrix Multiplication:\n", matrix_multiplication)

Matrix 1:
 [[1 2]
 [3 4]]


Matrix 2: 
 [[5 6]
 [7 8]]


Matrix Multiplication:
 [[19 22]
 [43 50]]


 Explanation: For matrix1 = [[1, 2], [3, 4]] and matrix2 = [[5, 6], [7, 8]], the product is:
        
        Row 1 * Column 1: (1*5 + 2*7) -> 19
        Row 1 * Column 2: (1*6 + 2*8) -> 22
        Row 2 * Column 1: (3*5 + 4*7) -> 43
        Row 2 * Column 2: (3*6 + 4*8) -> 50

Result:
[[19, 22],
 [43, 50]]

#### Transpose of a Matrix
The transpose of a matrix flips its rows and columns.

In [16]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

transpose = matrix1.T

print("Matrix 1:\n", matrix1)
print("\n")
print("Matrix 2: \n", matrix2)
print("\n")
print("Transpose of Matrix 1:\n", transpose)

Matrix 1:
 [[1 2]
 [3 4]]


Matrix 2: 
 [[5 6]
 [7 8]]


Transpose of Matrix 1:
 [[1 3]
 [2 4]]
