**Importing the Dependencies**

In [1]:
import numpy as np
import pandas as pd

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

**Importing the Models**

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

**Data Collection and Processing**

In [4]:
# loading the csv data to a Pandas DataFrame
heart_data = pd.read_csv('/content/heart.csv')

In [5]:
# print first 5 rows of the dataset
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [6]:
# number of rows and columns in the dataset
heart_data.shape

(303, 14)

In [7]:
# checking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
# checking the distribution of Target Variable
heart_data['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

1 --> Defective Heart

0 --> Healthy Heart

**Splitting the Features and Target**

In [9]:
X = heart_data.drop(columns='target', axis = 1)
y = heart_data['target']

In [10]:
print(X)

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  
0        0   0     1  
1        0   0     2  
2        2   0    

In [11]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64


# **Train Test Split**

---



In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y, random_state = 3)

In [13]:
X.shape, X_train.shape, X_test.shape

((303, 13), (242, 13), (61, 13))

## **Comparing the performance of the models**

---



**Logistic Regression**

In [14]:
logR_model = LogisticRegression(max_iter=1000)

In [15]:
logR_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [19]:
y_predict = logR_model.predict(X_test)

In [20]:
logR_accuracy = accuracy_score(y_test, y_predict)

In [21]:
logR_accuracy

0.7704918032786885

In [28]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.77      0.71      0.74        28
           1       0.77      0.82      0.79        33

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61



In [30]:
print(confusion_matrix(y_test, y_predict))

[[20  8]
 [ 6 27]]


**Support Vector Machine Classifier**

In [24]:
svc_model = SVC(kernel='linear', C=1.0)

In [25]:
svc_model.fit(X_train, y_train)

SVC(kernel='linear')

In [26]:
y_pred = svc_model.predict(X_test)

In [27]:
svc_accuracy = accuracy_score(y_test, y_pred)

In [31]:
svc_accuracy

0.7704918032786885

In [32]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.68      0.73        28
           1       0.76      0.85      0.80        33

    accuracy                           0.77        61
   macro avg       0.77      0.76      0.77        61
weighted avg       0.77      0.77      0.77        61



In [33]:
print(confusion_matrix(y_test, y_pred))

[[19  9]
 [ 5 28]]


**K-Nearest Neighbors Classifier**

In [34]:
KNN_model = KNeighborsClassifier()

In [35]:
KNN_model.fit(X_train, y_train)

KNeighborsClassifier()

In [37]:
y_pred = KNN_model.predict(X_test)

In [38]:
knn_accuracy = accuracy_score(y_test, y_pred)

In [39]:
knn_accuracy

0.6557377049180327

In [40]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.64      0.57      0.60        28
           1       0.67      0.73      0.70        33

    accuracy                           0.66        61
   macro avg       0.65      0.65      0.65        61
weighted avg       0.65      0.66      0.65        61



In [41]:
print(confusion_matrix(y_test, y_pred))

[[16 12]
 [ 9 24]]


**Random Forest Classifier**

In [42]:
rfc_model = RandomForestClassifier()

In [43]:
rfc_model.fit(X_train, y_train)

RandomForestClassifier()

In [44]:
y_pred = rfc_model.predict(X_test)

In [45]:
rfc_accuracy = accuracy_score(y_test, y_pred)

In [46]:
rfc_accuracy

0.7868852459016393

In [47]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.71      0.75        28
           1       0.78      0.85      0.81        33

    accuracy                           0.79        61
   macro avg       0.79      0.78      0.78        61
weighted avg       0.79      0.79      0.79        61



In [48]:
print(confusion_matrix(y_test, y_pred))

[[20  8]
 [ 5 28]]


## **Cross Validation**

---



**Logistic Regression**

In [49]:
cv_score_lr = cross_val_score(logR_model, X, y, cv = 5)

In [50]:
print(cv_score_lr)

[0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]


In [51]:
mean_accuracy_lr = sum(cv_score_lr) / len(cv_score_lr)

In [52]:
mean_accuracy_lr = mean_accuracy_lr * 100

In [53]:
mean_accuracy_lr = round(mean_accuracy_lr, 2)

In [54]:
print(mean_accuracy_lr)

82.83


**Support Vector Classifier**

In [55]:
cv_score_svc = cross_val_score(svc_model, X, y, cv=5)

In [56]:
print(cv_score_svc)

[0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]


In [57]:
mean_accuracy_svc = sum(cv_score_svc) / len(cv_score_svc)

In [58]:
mean_accuracy_svc = mean_accuracy_svc * 100

In [59]:
mean_accuracy_svc = round(mean_accuracy_svc, 2)

In [60]:
print(mean_accuracy_svc)

82.83


**K-Nearest Neighbors Classifier**

In [62]:
cv_score_knn = cross_val_score(KNN_model, X, y, cv=5)

In [63]:
print(cv_score_knn)

[0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]


In [64]:
mean_accuracy_knn = sum(cv_score_knn) / len(cv_score_knn)

In [65]:
mean_accuracy_knn = mean_accuracy_knn * 100

In [66]:
mean_accuracy_knn = round(mean_accuracy_knn, 2)

In [67]:
mean_accuracy_knn

64.39

**Random Forest Classifier**

In [68]:
cv_score_RFC = cross_val_score(rfc_model, X, y, cv=5)

In [69]:
print(cv_score_RFC)

[0.83606557 0.8852459  0.7704918  0.83333333 0.75      ]


In [70]:
mean_accuracy_RFC = sum(cv_score_RFC) / len(cv_score_RFC)

In [71]:
mean_accuracy_RFC = mean_accuracy_RFC * 100

In [72]:
mean_accuracy_RFC = round(mean_accuracy_RFC, 2)

In [73]:
mean_accuracy_RFC

81.5

## **Comparing the performance of the models**

---



In [74]:
# list of models
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [75]:
def compare_models_train_test():

  for model in models:

    # training the model
    model.fit(X_train, y_train)

    # evaluating the model
    test_data_prediction = model.predict(X_test)

    accuracy = accuracy_score(y_test, test_data_prediction)

    print('Accuracy score of the ', model, ' = ', accuracy)

In [76]:
compare_models_train_test()

Accuracy score of the  LogisticRegression(max_iter=1000)  =  0.7704918032786885
Accuracy score of the  SVC(kernel='linear')  =  0.7704918032786885
Accuracy score of the  KNeighborsClassifier()  =  0.6557377049180327
Accuracy score of the  RandomForestClassifier()  =  0.7704918032786885


## **Creating a Function to compare the models**

---



In [77]:
# list of models
models = [LogisticRegression(max_iter=1000), SVC(kernel='linear'), KNeighborsClassifier(), RandomForestClassifier()]

In [80]:
def compare_models_cross_validation():

  for model in models:

    cv_score = cross_val_score(model, X,y, cv=5)

    mean_accuracy = sum(cv_score)/len(cv_score)

    mean_accuracy = mean_accuracy*100

    mean_accuracy = round(mean_accuracy, 2)

    print('Cross Validation accuracies for ', model, '=  ', cv_score)
    print('Accuracy % of the ', model, mean_accuracy)
    print('----------------------------------------------')

In [81]:
compare_models_cross_validation()

Cross Validation accuracies for  LogisticRegression(max_iter=1000) =   [0.80327869 0.86885246 0.85245902 0.86666667 0.75      ]
Accuracy % of the  LogisticRegression(max_iter=1000) 82.83
----------------------------------------------
Cross Validation accuracies for  SVC(kernel='linear') =   [0.81967213 0.8852459  0.80327869 0.86666667 0.76666667]
Accuracy % of the  SVC(kernel='linear') 82.83
----------------------------------------------
Cross Validation accuracies for  KNeighborsClassifier() =   [0.60655738 0.6557377  0.57377049 0.73333333 0.65      ]
Accuracy % of the  KNeighborsClassifier() 64.39
----------------------------------------------
Cross Validation accuracies for  RandomForestClassifier() =   [0.85245902 0.90163934 0.80327869 0.81666667 0.76666667]
Accuracy % of the  RandomForestClassifier() 82.81
----------------------------------------------
