In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [3]:
from sklearn.model_selection import train_test_split

In [5]:
import statistics as st

In [6]:
# load dataset
df = pd.read_csv('/content/heart.csv')

In [7]:
# spliting the dataset
x = df.drop(columns='target', axis = 1)
y = df['target']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state= 0)

## **Models Creation and Train the Model**

---



**Decision Tree Classifier**

In [10]:
model1 = DecisionTreeClassifier()

In [11]:
model1.fit(X_train, y_train)

DecisionTreeClassifier()

**K - Nearest Neighbors Classifier**

In [12]:
model2 = KNeighborsClassifier()

In [13]:
model2.fit(X_train, y_train)

KNeighborsClassifier()

**Logistic Regression**

In [16]:
model3 = LogisticRegression(max_iter=1000)

In [17]:
model3.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

**Prediction Using Every Model**

In [18]:
pred1 = model1.predict(X_test)

In [19]:
pred1

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [20]:
pred2 = model2.predict(X_test)

In [21]:
pred2

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0])

In [22]:
pred3 = model3.predict(X_test)

In [23]:
pred3

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

**Final Prediction**

In [25]:
final_pred = np.array([])
for i in range(0, len(X_test)):
  final_pred = np.append(final_pred, st.mode([pred1[i], pred2[i], pred3[i]]))

In [26]:
print(final_pred)

[0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 0. 1. 1. 0. 0. 0.
 1. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 1. 1.
 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]


## **Alternatively, can use "Voting Classifier" module**

---



In [27]:
from sklearn.ensemble import VotingClassifier

In [33]:
model1 = LogisticRegression(random_state=1, max_iter= 1000)

In [29]:
model2 = DecisionTreeClassifier(random_state=1)

In [30]:
model3 = KNeighborsClassifier()

In [34]:
model = VotingClassifier(estimators=[('lr', model1), ('dt', model2), ('knn', model3)], voting='hard')

In [35]:
model.fit(X_train,  y_train)

VotingClassifier(estimators=[('lr',
                              LogisticRegression(max_iter=1000,
                                                 random_state=1)),
                             ('dt', DecisionTreeClassifier(random_state=1)),
                             ('knn', KNeighborsClassifier())])

In [36]:
model.score(X_test, y_test)

0.819672131147541

In [37]:
from sklearn.metrics import classification_report

In [38]:
print(classification_report(y_test, final_pred))

              precision    recall  f1-score   support

           0       0.88      0.78      0.82        27
           1       0.84      0.91      0.87        34

    accuracy                           0.85        61
   macro avg       0.86      0.84      0.85        61
weighted avg       0.85      0.85      0.85        61

