#### Importing numpy library

In [1]:
import numpy as np

#### Build Support Vector Machine Classifier

In [28]:
class SVM_Classifier():
    
    def __init__(self, learning_rate, no_of_iteration, lambda_parameter):
        self.learning_rate = learning_rate
        self.no_of_iteration = no_of_iteration
        self.lambda_parameter = lambda_parameter
    
    def fit(self, X, Y):
        self.m, self.n = X.shape
        
        self.w = np.zeros(self.n)
        self.b = 0
        self.X = X
        self.Y = Y
        
        for i in range(self.no_of_iteration):
            self.update_weights()
        
    def update_weights(self):
        y_label = np.where(self.Y <= 0, -1, 1)
        
        for index, x_i in enumerate(self.X):
            condition = y_label[index] * (np.dot(x_i, self.w) - self.b) >= 1
            
            if (condition == True):
                dw = 2 * self.lambda_parameter * self.w
                db = 0
            
            else:
                dw = 2 * self.lambda_parameter * self.w - np.dot(x_i, y_label[index])
                db = y_label[index]
            
            self.w = self.w - self.learning_rate * dw
            self.b = self.b - self.learning_rate * db
    
    def predict(self, X):
        output = np.dot(X, self.w) - self.b
        predicted_labels = np.sign(output)
        y_hat = np.where(predicted_labels <= -1, 0, 1)
        
        return y_hat

#### Importing the Dependencies

In [4]:
import pandas as pd

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#### Data Collection and Preprocessing

In [7]:
# loading the data from csv file to pandas dataframe
diabetes_data = pd.read_csv('G:\\Data Bases For 99DaysWithCPC\\Building Machine Learning model\\SVMC\\diabetes.csv')

In [8]:
# print the first 5 rows of the dataframe
diabetes_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [9]:
# number of rows and columns in the dataset
diabetes_data.shape

(768, 9)

In [10]:
# getting the statistical measures of the dataset
diabetes_data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [11]:
diabetes_data['Outcome'].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [13]:
# separating the features and target
features = diabetes_data.drop(columns='Outcome', axis=1)
target = diabetes_data['Outcome']

In [14]:
features

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

In [15]:
target

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

#### Data Standardization

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(features)

StandardScaler()

In [18]:
standardized_data = scaler.transform(features)

In [19]:
standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [20]:
features = standardized_data
target = diabetes_data['Outcome']

#### Train Test Split

In [21]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=2)

In [22]:
features.shape, X_train.shape, X_test.shape

((768, 8), (614, 8), (154, 8))

#### Training The Model using SVMC

In [29]:
svmc_model = SVM_Classifier(learning_rate=0.001, no_of_iteration=1000, lambda_parameter=0.01)

In [30]:
# training the SVM classifier with training data
svmc_model.fit(X_train, y_train)

#### Model Evaluation
###### Accuracy Score

In [31]:
# accuracy on training data
X_train_prediction = svmc_model.predict(X_train)
training_data_accuracy = accuracy_score(y_train, X_train_prediction)

In [32]:
training_data_accuracy

0.7768729641693811

In [33]:
# accuracy on testing data
X_test_prediction = svmc_model.predict(X_test)
test_data_accuracy = accuracy_score(y_test, X_test_prediction)

In [34]:
test_data_accuracy

0.7532467532467533

#### Building a Predictive System

In [35]:
# Input data
input_data = (5, 166, 72, 19, 175, 25.8, 0.587, 51)

In [37]:
# Create a DataFrame with column names
input_data_df = pd.DataFrame([input_data], columns=diabetes_data.columns.drop('Outcome'))

In [38]:
# Display the DataFrame
input_data_df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            5      166             72             19      175  25.8   

   DiabetesPedigreeFunction  Age  
0                     0.587   51

In [39]:
# standardized the data
std_data = scaler.transform(input_data_df)

In [40]:
std_data

array([[ 0.3429808 ,  1.41167241,  0.14964075, -0.09637905,  0.82661621,
        -0.78595734,  0.34768723,  1.51108316]])

In [41]:
# predict the Outcome
prediction = svmc_model.predict(std_data)

In [42]:
prediction

array([1])

In [43]:
# Output the result
if prediction[0] == 0:
    print('The person is not diabetic')
else:
    print('The Person is diabetic')

The Person is diabetic


In [44]:
from sklearn.metrics import confusion_matrix

In [45]:
print(confusion_matrix(y_test, X_test_prediction))

[[96 13]
 [25 20]]
